Free list returned by wlan_sta_scan_result()
libretiny-eu/libretiny pull request #226
Opened 2023-12-23 00:09 UTC by szupi-ipuzs

This method might return a dynamically allocated buffer which should be freed by the caller (the example code does it). Not doing this results in memory leaks.

2023-12-23 00:12 UTC, szupi-ipuzs commented on cores/beken-72xx/arduino/libraries/WiFi/WiFiScan.cpp
> +		free(result.ApList);
The sdk code allocates this mem using some os-independent wrappers. I'm pretty sure they all and up calling malloc() or calloc(), so its safe to call free() on it - but please someone double check it.

2023-12-23 01:53 UTC, szupi-ipuzs commented on cores/realtek-amb/arduino/libraries/WiFi/WiFiScan.cpp
>  		return RTW_SUCCESS;
I can see this function always returns RTW_SUCCESS, even on error. Is this intended?

2024-01-03 21:26 UTC, kuba2k2 commented on cores/beken-72xx/arduino/libraries/WiFi/WiFiScan.cpp
> +		free(result.ApList);
Yes, all wrappers I've seen so far use FreeRTOS eventually. And the standard library memmang functions are linked to FreeRTOS as well, so it's perfectly safe to use `free()` here.

2024-01-03 21:37 UTC, kuba2k2 requested changes

2024-01-03 21:37 UTC, kuba2k2 commented on cores/common/arduino/libraries/api/WiFi/WiFi.h
> -	uint8_t scanAlloc(uint8_t count);
These are Arduino APIs, we're not supposed to change the function signatures or behavior. As unfortunate as it is (the APIs are pretty badly designed IMHO), doing otherwise may cause undesired problems with compilation if the user's code uses these methods for some reason.

2024-01-03 21:37 UTC, kuba2k2 commented on cores/realtek-amb/arduino/libraries/WiFi/WiFiScan.cpp
>  		return RTW_SUCCESS;
Probably; this is a scanning callback called by the SDK, I don't even think it cares about errors. So the return value is most likely meaningless, and returning an error code would likely cause some other problems.

2024-01-03 23:14 UTC, szupi-ipuzs commented on cores/common/arduino/libraries/api/WiFi/WiFi.h
> -	uint8_t scanAlloc(uint8_t count);
I was afraid of something like that.
I do not see any description of the return value, but returning the previous count does not allow this method to indicate an error. And, correct me if i'm wrong, failure to allocate a memory should be quite common on systems like that, so it is important to know that and react (eg. by retrying or at least not writing to the memory area).
So, I would strongly suggest changing the API even risking breaking the user's code.

Alternatively, if it is only the method's signature that must remain the same, I suggest returning instead the count of items that we successfully allocated. Then the user can compare it to what was requested and judge by that. What do you think?

2024-01-03 23:14 UTC, szupi-ipuzs commented on cores/realtek-amb/arduino/libraries/WiFi/WiFiScan.cpp
>  		return RTW_SUCCESS;
I've just checked and it appears that you're right - the SDK completely ignores the value returned by this callback. So for the sake of consistency it's better to always return RTW_SUCCESS.

2024-01-03 23:27 UTC, kuba2k2 commented on cores/common/arduino/libraries/api/WiFi/WiFi.h
> -	uint8_t scanAlloc(uint8_t count);
Actually, upon checking I see that there's no such method in ESP32 at all:
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiScan.h

Sorry for the confusion. I must have taken the wifi library from somewhere else then, because I don't think I'd ever write a function with such a weird return value.

Of course, you're free to keep your changes in this case. This function could even be made private now - no other class is supposed to use it anyway.

2024-01-04 00:49 UTC, szupi-ipuzs commented
Ok, as you can see I decided to make the scanAlloc() method return the number of succesfully allocated items. This can help if realloc() fails - then we still can use the previously allocated buffer if needed.
Making this method private should be done as a separate change, since it probably isn't the only one that should be moved.

I have tested this code shortly on bk7231, but not on realtek, since I do not own any realtek device atm (only checked compilation).

2024-01-06 18:21 UTC, kuba2k2 approved these changes

2024-01-06 18:41 UTC, merged