Fix math for deep_sleep time param
libretiny-eu/libretiny pull request #232
Opened 2024-01-01 14:09 UTC by daniel-dona

Fix for #230

2024-01-03 18:30 UTC, kuba2k2 requested changes

2024-01-03 18:30 UTC, kuba2k2 commented on cores/beken-72xx/base/api/lt_sleep.c
> +	uint32_t duration_math = (32768 * ((float) sleep_duration)/1000.0);
To avoid unnecessary casting, could you try `32.768 * sleep_duration`? This way the division is avoided, and casting is implicit because the first operand is a float.

2024-01-03 18:30 UTC, kuba2k2 commented on cores/beken-72xx/base/api/lt_sleep.c
> +	if (duration_math > 0xFFFFFFFF) {
This can never be larger than 0xFFFFFFFF now. Is that even needed?

2024-03-05 14:25 UTC, Cossid commented
This can probably be closed as duplicate of the now-completed #253

2024-03-05 14:33 UTC, closed without merging