Updates to break out wakeup reasons.
libretiny-eu/libretiny pull request #254
Opened 2024-02-21 02:53 UTC by cap9qd

Per https://github.com/libretiny-eu/libretiny/issues/234

2024-02-21 11:51 UTC, kuba2k2 requested changes

2024-02-21 11:51 UTC, kuba2k2 commented on cores/common/base/api/lt_device.h
> +#define RESET_REASON_SLEEP_GPIO	  REBOOT_REASON_SLEEP_USB
Typo - same #define names.

2024-02-21 11:51 UTC, kuba2k2 commented on cores/common/base/api/lt_device.h
> +	REBOOT_REASON_SLEEP_GPIO = 8,
Please also keep the previous `REBOOT_REASON_SLEEP` name (same in #defines above). It can have the same value as `REBOOT_REASON_SLEEP_GPIO`.
It can be added as a separate #define below the enum, and marked with a comment that it's deprecated. This way code that relies on this will not break.

2024-02-21 15:43 UTC, cap9qd commented on cores/common/base/api/lt_device.h
> +#define RESET_REASON_SLEEP_GPIO	  REBOOT_REASON_SLEEP_USB
Fixed.

2024-02-21 15:43 UTC, cap9qd commented on cores/common/base/api/lt_device.h
> +	REBOOT_REASON_SLEEP_GPIO = 8,
I was wondering about how to do this. Should be fixed now.

2024-02-22 19:26 UTC, kuba2k2 requested changes

2024-02-22 19:26 UTC, kuba2k2 commented on cores/common/base/api/lt_device.h
> +#define RESET_REASON_SLEEP REBOOT_REASON_SLEEP_GPIO
Please also include the previous `REBOOT_REASON_SLEEP` name here (as a #define).

2024-02-22 19:26 UTC, kuba2k2 commented on cores/common/base/api/lt_device.h
> +//RESET_REASON_SLEEP depricated
```suggestion
// RESET_REASON_SLEEP deprecated, kept for compatibility
```

2024-02-22 19:27 UTC, kuba2k2 commented
clang-format needs fixes here:
https://github.com/libretiny-eu/libretiny/actions/runs/7991708089/job/21879639566?pr=254

2024-02-23 01:38 UTC, cap9qd commented
> clang-format needs fixes here: https://github.com/libretiny-eu/libretiny/actions/runs/7991708089/job/21879639566?pr=254

I have the clang-format fixed. The python one still seems to fail but I didn't change anything there...?

2024-02-23 15:18 UTC, kuba2k2 commented on cores/common/base/api/lt_device.h
> +#define RESET_REASON_SLEEP REBOOT_REASON_SLEEP_GPIO
Unfortunately, this macro is still missing in the latest changes.

2024-02-23 16:01 UTC, cap9qd commented on cores/common/base/api/lt_device.h
> +#define RESET_REASON_SLEEP REBOOT_REASON_SLEEP_GPIO
I'm sorry for missing that! I thought I accepted the change and committed it.

2024-02-23 16:50 UTC, cap9qd commented on cores/common/base/api/lt_device.h
@kuba2k2 Is this what you mean?

2024-02-23 18:16 UTC, kuba2k2 commented on cores/common/base/api/lt_device.h
Yes

2024-02-25 17:44 UTC, kuba2k2 approved these changes

2024-02-25 17:45 UTC, merged