Fixed unsafe conversion to underscore string
libretiny-eu/libretiny pull request #260
Opened 2024-03-01 19:46 UTC by szupi-ipuzs

strcpy() always adds null-terminator at the end.
The original code allocated one byte less than what is needed, so it was overwriting _something_. Could've been important or not :)
Found this while debugging #248, but I don't know if it fixes it or not. In my local tests on ubuntu I was not able to reproduce the behavior described in #248. But if it's memory related, then it's bound to behave differently on x86 + linux. Worth checking if it helped.

2024-03-01 19:57 UTC, Cossid commented on cores/common/arduino/libraries/common/mDNS/mDNS.cpp
> +	uint8_t len	 = strlen(value) + 1 + 1; // 1 for underscore, 1 for null-terminator
Should this be conditional on `value[0] == '_'` (or `!=`) like below for that extra 1?
Granted malloc'ing 1 extra byte isnt the end of the world, and it's free'd relatively soon after anyway.

2024-03-01 20:10 UTC, Cossid commented on cores/common/arduino/libraries/common/mDNS/mDNS.cpp
> +	uint8_t len	 = strlen(value) + 1 + 1; // 1 for underscore, 1 for null-terminator
yeah, `if (value[0] == '_') return value;` seems like the better optimization.

2024-03-02 10:51 UTC, kuba2k2 requested changes

2024-03-02 10:51 UTC, kuba2k2 commented on cores/common/arduino/libraries/common/mDNS/mDNS.cpp
> +static void freeIfDuplicate(const char *original, const char *duplicate) {
A better name could be `freeIfCopied` - I only realized why it frees if `original != duplicate` after a few minutes. Somehow "duplicate" makes me think of it as "equal" or "the same".

Also, try making it inline for performance reasons.

2024-03-03 00:21 UTC, szupi-ipuzs commented on cores/common/arduino/libraries/common/mDNS/mDNS.cpp
> +static void freeIfDuplicate(const char *original, const char *duplicate) {
I misspelled, I should've named it duplicated, which is a synonim for copied. But copied is fine too.

2024-03-04 20:25 UTC, kuba2k2 requested changes

2024-03-04 20:25 UTC, kuba2k2 commented on cores/common/arduino/libraries/common/mDNS/mDNS.cpp
> +static inline void freeIfCopied(const char *original, const char *duplicate) {
I'm not sure if it makes sense to use `const char*` in this unit. Freeing const pointers is forbidden, hence the need for a type cast. These strings are allocated on the heap, they're not stored in code memory or R/O memory.

2024-03-04 20:59 UTC, szupi-ipuzs commented on cores/common/arduino/libraries/common/mDNS/mDNS.cpp
> +static inline void freeIfCopied(const char *original, const char *duplicate) {
According to clean code you should really const every parameter that is not supposed to be changed by the method. And you're right, for the "duplicate" the const doesn't make sense, as it actually _is_ modified (ie. freed).
But "original" should not be touched, so I would leave the other const there.

2024-03-04 21:02 UTC, szupi-ipuzs commented on cores/common/arduino/libraries/common/mDNS/mDNS.cpp
> +static inline void freeIfCopied(const char *original, const char *duplicate) {
By the way, since this is c++ why all this playing with manually allocated c-strings? This is very error-prone. Doesn't arduino have a String class?

2024-03-04 21:19 UTC, kuba2k2 commented on cores/common/arduino/libraries/common/mDNS/mDNS.cpp
> +static inline void freeIfCopied(const char *original, const char *duplicate) {
It does, but I believe in Holy-C

Jokes aside, Arduino Strings tend to be a huge performance and RAM bottleneck. I'd even be better off using C++ strings than Arduino strings - heck, even the feature set of these isn't enforced and constant among platforms.

At some point, LibreTiny will get a real C++ low-level API, then there'll be a good time to play with modern C++ features :smiley: The Arduino APIs in LibreTiny are unfortunately meant to be "compatible" (with software that depends on it), not "good".

2024-03-05 20:17 UTC, szupi-ipuzs commented
Ok, I think this is enough improvements for now. The only thing left would be to call the new cleanup() method somewhere. In current implementation it will only be called in destructor, but since this is a static object that would be... never?
Shouldn't the mDNS.end() be called in MDNSComponent::on_shutdown() (in mdns_libretiny.cpp)? That would call cleanup right about when it should be, right? Currently it isn't called at all if I'm not mistaken.

2024-03-05 21:06 UTC, kuba2k2 commented
That's the problem in embedded/IoT programming - these devices most often run as long as they're given power. There's no shutdown, no close button. ESPHome probably never actually calls the shutdown method under normal circumstances, because why would it?
The point is, with the current Arduino API, there's only so much you can improve. I'd say it's okay the way it is and that there's no need to worry about this.

2024-03-07 23:36 UTC, szupi-ipuzs commented
I work in embedded for some time now and I've seen this "we won't need a shutdown" approach many times. And in many cases we eventually did need it :), only by then it was very hard to achieve due to many decisions like not doing proper deregistration or deallocations, using static objects and singletons.

And the reasons for needing this in embedded is one: to prevent a full reboot, which usually comes with a price of having to re-initialize and re-register everything, while the only thing you wanted was to reinitialize one small component.

The fact that esphome component does have a shutdown method means they are thinking about having this, so I would say it's worth to be prepared :)

2024-03-08 10:58 UTC, kuba2k2 commented
Right, but that's a topic for another PR anyway :slightly_smiling_face:

2024-03-08 11:01 UTC, kuba2k2 approved these changes

2024-03-08 11:21 UTC, merged